AllCops:
  Exclude:
    - bin/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - Guardfile
    - .gems/**/*

Rails:
  Enabled: true

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 20

Metrics/AbcSize:
  Max: 80

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/TimeZone:
  Enabled: false

Rails/Delegate:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/PredicateName:
  Enabled: false

Metrics/MethodLength:
  Max: 50
  Exclude:
    - 'spec/support/object_mocks.rb'

Lint/AssignmentInCondition:
  Enabled: false

Lint/NestedMethodDefinition:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 30

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
  Enabled: true

Metrics/BlockLength:
  Max: 150

Rails/SkipsModelValidations:
  Enabled: false

Security/YAMLLoad:
  Exclude:
    - 'spec/**/**'

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/ClassLength:
  Max: 400

Metrics/ParameterLists:
  Max: 15

Style/MethodMissing:
  Exclude:
    - 'config/boot.rb'
